language: node_js
node_js:
  - 15

services: docker

install:
  - echo "Nothing needs to be installed 😀"

before_script:
  - echo "no scripts to run before build"

script:
  - docker --version # helpful for troubleshooting
  - docker build -t udagram-feed-api ./feed-api/.
  - docker tag udagram-feed-api marcusholmgren/udagram-feed-api:latest
  - docker build -t udagram-user-api ./user-api/.
  - docker tag udagram-user-api marcusholmgren/udagram-user-api:latest
  - docker build -t udagram-proxy-api ./proxy-api/.
  - docker tag udagram-proxy-api marcusholmgren/udagram-proxy-api:latest
  - docker build -t udagram-client ./frontend/.
  - docker tag udagram-client marcusholmgren/udagram-client:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push marcusholmgren/udagram-feed-api
  - docker push marcusholmgren/udagram-user-api
  - docker push marcusholmgren/udagram-proxy-api
  - docker push marcusholmgren/udagram-client
