version: "3.8"
services:
  image_filtering:
    build: ./image_filtering
    image: image-service:latest

    ports:
      - "8082:8082"

  feedapi:
    build: ./feed-api
    image: udagram-feed-api:latest
    depends_on:
      - postgres
    environment:
      - USERNAME=postgres
      - PASSWORD=password
      - DATABASE=postgres
      - HOST=postgres
      - DIALECT=postgres
    ports:
      - "8080:8080"

  userapi:
    build: ./user-api
    image: udagram-user-api:latest
    depends_on:
      - postgres
    environment:
      - USERNAME=postgres
      - PASSWORD=password
      - DATABASE=postgres
      - HOST=postgres
      - DIALECT=postgres
    ports:
      - "8081:8080"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
