version: "3.8"
services:
  udagramapi:
    build: ./proxy-api
    image: udagram-proxy-api:latest
    depends_on:
      - feedapi
      - userapi
    ports:
      - "8080:8080"

  image_filtering:
    build: ./image_filtering
    image: image-service:latest

    ports:
      - "8082:8082"

  feedapi:
    build: ./feed-api
    image: udagram-feed-api:latest
    depends_on:
      - postgres
    volumes:
      - ~/.aws/:/root/.aws:ro
    environment:
      - USERNAME=postgres
      - PASSWORD=password
      - DATABASE=postgres
      - HOST=postgres
      - DIALECT=postgres
      - JWT_SECRET=superunsecure
      - AWS_REGION=eu-central-1
      - AWS_PROFILE=default
      - AWS_MEDIA_BUCKET=udagram-marcus-dev

  userapi:
    build: ./user-api
    image: udagram-user-api:latest
    depends_on:
      - postgres
    environment:
      - USERNAME=postgres
      - PASSWORD=password
      - DATABASE=postgres
      - HOST=postgres
      - DIALECT=postgres
      - JWT_SECRET=superunsecure

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
