version: "3.8"
services:
  udagram-proxy-api:
    build: ./proxy-api
    image: udagram-proxy-api:latest
    depends_on:
      - udagram-feed-api
      - udagram-user-api
    ports:
      - "8080:8080"

#  udagram_image_filtering:
#    build: ./image_filtering
#    image: image-service:latest
#
#    ports:
#      - "8082:8082"

  udagram-feed-api:
    build: ./feed-api
    image: udagram-feed-api:latest
    depends_on:
      - postgres
    volumes:
      - ~/.aws/:/root/.aws:ro
    environment:
      - USERNAME=postgres
      - PASSWORD=password
      - DATABASE=postgres
      - HOST=postgres
      - DIALECT=postgres
      - JWT_SECRET=superunsecure
      - AWS_REGION=eu-central-1
      - AWS_PROFILE=default
      - AWS_MEDIA_BUCKET=udagram-marcus-dev

  udagram-user-api:
    build: ./user-api
    image: udagram-user-api:latest
    depends_on:
      - postgres
    environment:
      - USERNAME=postgres
      - PASSWORD=password
      - DATABASE=postgres
      - HOST=postgres
      - DIALECT=postgres
      - JWT_SECRET=superunsecure

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
