GET http://localhost:8082

###

GET http://localhost:8082/filteredimage

###

GET http://localhost:8082/filteredimage?image_url=a


###

GET http://localhost:8082/filteredimage?image_url=https://www.brfimatra.se/undraw/undraw_Documents_re_isxv.png

###

GET http://localhost:8082/filteredimage?image_url=https://upload.wikimedia.org/wikipedia/commons/b/bd/Golden_tabby_and_white_kitten_n01.jpg

###

GET http://UdagramMarcusDev-env-1.eba-9cmsxvm2.eu-central-1.elasticbeanstalk.com/filteredimage?image_url

#=https://www.brfimatra.se/undraw/undraw_Documents_re_isxv.png

###

POST http://localhost:8080/api/v0/feed
Content-Type: application/json

{
"caption": "abc",
  "url": "http://localhost:8080/cat.jpg"
}


###

curl -X GET http://localhost:8082/filteredimage\?image_url\=https://upload.wikimedia.org/wikipedia/commons/b/bd/Golden_tabby_and_white_kitten_n01.jpg --output t ./filtered_image.jpg

curl -X GET http://localhost:8082/filteredimage\?image_url\=https://upload.wikimedia.org/wikipedia/commons/b/bd/Golden_tabby_and_white_kitten_n01.jpg \
 -o filtered_image.jpg



###

GET http://localhost:8080/api/v0/feed


###

GET http://localhost:8080/api/v0/feed/1

###

PATCH http://localhost:8080/api/v0/feed/1
Content-Type: application/json

[
  { "op": "update", "variable": "caption", "value": "Hello" }
]




###

[
    { "op": "update", "variable": "caption", "value": "Marcus Holmgren" }
]


###

POST http://localhost:8080/api/v0/feed
Content-Type: application/json

{
  "caption": "hej",
  "url": "test.jpg"
}

###

GET https://fsts.skandia.se/as/authorization.oauth2
Client-Id: abc123

###

# curl -X GET --location "https://fsts.skandia.se/as/authorization.oauth2"
#    -H "Client-Id: abc123"
GET https://fsts.skandia.se/as/authorization.oauth2
Client-Id: abc123

###

GET http://localhost:8080/api/v0/users/auth

###


