apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-feed-api
  template:
    metadata:
      labels:
        app: udagram-feed-api
    spec:
      containers:
      - name: udagram-feed-api
        image: marcusholmgren/udagram-feed-api
        envFrom:
          - configMapRef:
              name: udagram-config
        ports:
          - containerPort: 8080
