apiVersion: v1
kind: Service
metadata:
  name: udagram-client-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30081
  selector:
    app: udagram-client-app
