# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration and Delivery

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  image-filtering-build:
    name: Build The Image Filtering Microservice
    runs-on: ubuntu-latest
    env:
      working-dir: ./image_filtering

    steps:
    - uses: actions/checkout@v2
    - name: Client use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install dependencies
      run: npm install
      working-directory: ${{ env.working-dir }}
    - run: npm run build
      working-directory: ${{ env.working-dir }}
    - name: Upload The Image Filtering Microservice artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: image-filtering-microservice
        path: ${{ env.working-dir }}/www/**/*

  feed-api-build:
    name: Build The Feed REST API Microservice
    runs-on: ubuntu-latest
    env:
      working-dir: ./feed-api

    steps:
    - uses: actions/checkout@v2
    - name: Client use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install dependencies
      run: npm install
      working-directory: ${{ env.working-dir }}
    - run: npm run build
      working-directory: ${{ env.working-dir }}
    - name: Upload The Udagram Feed REST API Microservice artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: udagram-feed-api-microservice
        path: ${{ env.working-dir }}/www/**/*

  user-api-build:
    name: Build The User REST API Microservice
    runs-on: ubuntu-latest
    env:
      working-dir: ./user-api

    steps:
    - uses: actions/checkout@v2
    - name: Client use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install dependencies
      run: npm install
      working-directory: ${{ env.working-dir }}
    - run: npm run build
      working-directory: ${{ env.working-dir }}
    - name: Upload The Udagram User REST API Microservice artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: udagram-user-api-microservice
        path: ${{ env.working-dir }}/www/**/*
      env:
        CI: true
