# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration and Delivery

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  backend-build:
    name: Build The Image Filtering Microservice
    runs-on: ubuntu-latest
    env:
      working-dir: ./backend

    steps:
    - uses: actions/checkout@v2
    - name: Client use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
      working-directory: ${{ env.working-dir }}
    - run: npm run build
      working-directory: ${{ env.working-dir }}
      env:
        CI: true
    - name: 'Upload The Image Filtering Microservice build artifact'
        uses: 'actions/upload-artifact@v2'
          with:
            name: image-filtering-microservice ${{ matrix.node-version }}
            path: ${{ github.workspace }}/www/archive.zip
